name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          
      - name: Set git info
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
      - name: Add upstream remote
        run: git remote add upstream https://github.com/spliit-app/spliit.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream
          git fetch --tags upstream

      - name: Merge changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -m "Sync with upstream"
          git push origin main
        
      - name: Sync all branches
        run: |
          for branch in $(git branch -r | grep 'upstream/' | grep -v 'HEAD' | sed 's/upstream\///'); do
            if [ -z "$(git branch --list $branch)" ]; then
              git checkout -b $branch upstream/$branch
            else
              git checkout $branch
            fi
            git merge "upstream/$branch" --allow-unrelated-histories -m "Sync with upstream"
            git push origin "$branch"
          done

      - name: Sync all tags
        run: |
          git fetch --tags upstream
          git tag | xargs -n 1 git push origin
